routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('dashboards', DashboardController::class);

app/Models/Dashboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{
    use HasFactory;

    protected $table = 'dashboards';
    public $timestamps = true;

    protected $fillable = [
        'title',
        'owner',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dashboard;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | LIST
    |--------------------------------------------------------------------------
    */
    public function index()
    {
        $dashboards = Dashboard::get();
        return view('dashboards.index', compact('dashboards'));
    }

    /*
    |--------------------------------------------------------------------------
    | CREATE
    |--------------------------------------------------------------------------
    */
    public function create()
    {
        $users = User::all();
        return view('dashboards.create')->with('users', $users);
    }

    /*
    |--------------------------------------------------------------------------
    | STORE
    |--------------------------------------------------------------------------
    */
    public function store(Request $request)
    {
        $request->validate([
            'owner' => 'required',
            'title' => 'required',
        ]);

        Dashboard::create($request->all());
        return redirect()->route('dashboards.index')->with('success', 'Dashboard created successfully.');
    }

    /*
    |--------------------------------------------------------------------------
    | EDIT
    |--------------------------------------------------------------------------
    */
    public function edit(Dashboard $dashboard)
    {
        $users = User::all();
        return view('dashboards.edit', compact('dashboard'))->with('users', $users);;
    }

    /*
    |--------------------------------------------------------------------------
    | UPDATE
    |--------------------------------------------------------------------------
    */
    public function update(Request $request, Dashboard $dashboard)
    {
        $request->validate([
            'title' => 'required',
            'owner' => 'required',
        ]);
        $dashboard->update($request->all());

        return redirect()->route('dashboards.index')->with('success', 'Dashboard updated successfully');
    }
}

resources/views/dashboards/create.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create dashboard</title>
  </head>
  <body>
    <h1>Create dashboard</h1>
    @if(count($errors))
      <ul>
        @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    @endif
    <form action="{{ route('dashboards.store') }}" method="POST">@csrf
      <div>
        <label>Owner</label>
        <select name="owner">
          @foreach ($users as $user)
            <option value="{{ $user->name }}">{{ $user->name }}</option>
          @endforeach
        </select>
      </div>
      <div>
        <label>Title</label>
        <input type="text" name="title">
      </div>
      <button type="submit" >SAVE</button>
    </form>
  </body>
</html>

resources/views/dashboards/edit.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update dashboard</title>
  </head>
  <body>
    <h1>Update dashboard</h1>
    @if(count($errors))
      <ul>
        @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    @endif
    <form action="{{ route('dashboards.update', $dashboard->id) }}" method="POST"> @csrf @method('PUT')
      <div>
        <label>Owner</label>
        <select name="owner">
          @foreach ($users as $user)
            <option value="{{ $user->name }}">{{ $user->name }}</option>
          @endforeach
        </select>
      </div>
      <div>
        <label>Title</label>
        <input type="text" name="title" value="{{ $dashboard->title }}">
      </div>
      <button type="submit" >SAVE</button>
    </form>
  </body>
</html>

resources/views/dashboards/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>List of dashboards</title>
  </head>
  <body>
    @if(Session::has('success'))
      Message: {{ Session::get('success') }}
    @endif
    <h1>List of dashboards</h1>
    <a href="{{ route('dashboards.create') }}">
      <button>NEW</button>
    </a>
    <br />
    <br />
    <table border="1px" cellspacing="0px" style="width:100%;">
      <thead>
        <tr>
          <th class="text-center">ID</th>
          <th class="text-center">Owner</th>
          <th class="text-center">Title</th>
          <th class="text-center">Actions</th>
        </tr>
      </thead>
      <tbody>
      @foreach ($dashboards as $dashboard)
      <tr>
        <td class="text-center">{{ $dashboard->id }}</td>
        <td class="text-center">{{ $dashboard->owner }}</td>
        <td class="text-center">{{ $dashboard->title }}</td>
        <td>
          <a href="{{ route('dashboards.edit', $dashboard->id) }}">
            <button>UPDATE</button>
          </a>
        </td>
      </tr>
      @endforeach
      </tbody>
    </table>
  </body>
</html>